apiVersion: v1
kind: Service
metadata:
  name: webook-mysql
spec:
  selector:
    app: webook-mysql
  ports:
    - protocol: TCP
      name: http
      port: 81
      targetPort: 3306
  type: LoadBalancer
  